### ISSUE TITLE
$select operator

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#31]
Hi,

While testing the [$select](https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/main/test/ts/%24select.test.ts) operator, here's some findings..

1. For selecting multiple fields, should I use `string` or string[]`? Notice the different way to assign the `select` would yield the same result. So is there a proper way to do this? or are all these valid?

```js
const find2 = await Airplane.find(
	{},
	{
                // array of 1 string delimit with comma
		select: ['operational, callsign, name, info.numberOfFlightsSince'],
		consistency: SearchConsistency.LOCAL
	}
);

// return 
_Model {
      _type: 'Airplane',
      callsign: 'Hawk',
      name: 'Couchbase Airlines',
      numberOfFlightsSince: 10000,
      operational: true,
      scheduledAt: Invalid Date,
      capacity: 0
}
```

```js
const find2 = await Airplane.find(
	{},
	{
                // string delimit with comma
		select: 'operational, callsign, name, info.numberOfFlightsSince',
		consistency: SearchConsistency.LOCAL
	}
);

// return
_Model {
      _type: 'Airplane',
      callsign: 'Hawk',
      name: 'Couchbase Airlines',
      numberOfFlightsSince: 10000,
      operational: true,
      scheduledAt: Invalid Date,
      capacity: 0
}
```

```js
const find2 = await Airplane.find(
	{},
	{
                // array of string
		select: ['operational', 'callsign', 'name', 'info.numberOfFlightsSince'],
		consistency: SearchConsistency.LOCAL
	}
);

// return
_Model {
      _type: 'Airplane',
      callsign: 'Hawk',
      name: 'Couchbase Airlines',
      numberOfFlightsSince: 10000,
      operational: true,
      scheduledAt: Invalid Date,
      capacity: 0
}
```

---

2. Also notice from the output above, the `result` will return other fields as well but with some default values

I created using this dataset

```js
const hawk = {
    callsign: 'Hawk',
    name: 'Couchbase Airlines',
    operational: true,
    destination: ['Japan'],
    scheduledAt: new Date('20 Nov 2020 11:30'),
    capacity: 250,
    model: 'A380',
    size: 'S',
    info: {
        firstFlightAt: new Date('12 Jan 2010 13:10'),
        numberOfFlightsSince: 10000
    }
}
```

And the result from using `$select` seem to return `non-string` fields with default values (boolean set to true, number to 0, date to invalid date)

```js
_Model {
      _type: 'Airplane',
      callsign: 'Hawk',
      name: 'Couchbase Airlines',
      numberOfFlightsSince: 10000,
      // even though the fields below are not selected, but it returns with default values
      operational: true,
      scheduledAt: Invalid Date,
      capacity: 0
}
```

As far as I can tell, only `non-string` value are returned with default values.

```js
const find2 = await Airplane.find(
            {},
            {
                select: 'operational', // this is boolean
                consistency: SearchConsistency.LOCAL
            }
        );

// returns 
// no extra 'string' fields are returns
_Model {
      _type: 'Airplane',
      operational: true,
      scheduledAt: Invalid Date,
      capacity: 0
}
```

---

3. Slightly different behavior from `mongoose` and `ottoman`, this one I think is debatable, both aren't wrong (I think)

If I were to select `nested field`, this is what `mongoose` would return

```js
const find = await Airplane.find()
            .select('info.numberOfFlightsSince')
            .exec();

// returns
// notice it returns the original info object with only numberOfFlightsSince field
{
    info: { numberOfFlightsSince: 10000 },
    _id: 5fce3e920061d14f38172323
  }
```

And this is what `ottoman` does

```js
const find = await Airplane.find(
	{},
	{
		select: 'info.numberOfFlightsSince',
		consistency: SearchConsistency.LOCAL
	}
);

// returns
_Model {
      _type: 'Airplane',
      // only return the field, the original object is lost
      numberOfFlightsSince: 10000,
      operational: true,
      scheduledAt: Invalid Date,
      capacity: 0
}
```

What do you think of this?

Thanks!

**Comment by AV25242** [comment]
Hi @bwgjoseph  good in depth analysis with examples, cannot ask for more 

Let's split it into 3 questions  (if you think it makes sense) and we can go from here.

1 )  What is the most appropriate way of doing a SELECT ? 
2)   Why is find returning back field that were not in SELECT ?
3)  In the select when I query for an object why is the object not being returned but only the field is returned or in other words how can I get the object back ?

**Comment by bwgjoseph** [comment]
Yup, exactly.

Just a little addon for

1. I think it's fine to support multiple format but `array of 1 string delimit with comma` probably not one of them. So it could be either `select: 'a, b, c'` or `select: ['a', 'b', 'c']`. I would probably preferred the latter `select: ['a', 'b', 'c']`

3. After thinking through, I think it should return the field with the object back (as it make more sense)

```js
{
    info: { numberOfFlightsSince: 10000 },
    _id: 5fce3e920061d14f38172323
  }
```

Thanks!

**Comment by bwgjoseph** [comment]
From #29, 

Although it's nice to know that I can do { select: 'meta().id,travel-sample.*' }, can I just do { select: 'meta().id, *'} without the bucket name? Also, does it have to be bucket name? What if this is a scope/collection? I actually would rather to place just * though

To expand on this, can I query with just

{ select: 'meta().id, __*__' } instead of  { select: 'meta().id, **travel-sample**.*' } without needing to input the bucket/scope/collection prefix.

Currently, I can do the following  { select: 'meta().id, name, destination' } without needing me to query like such { select: 'meta().id, **travel-sample**.name, **travel-sample**.destination' } so I thought that having the prefix might not be required

**Comment by AV25242** [comment]
This need to be tried out @httpJunkie  can you please try this ?

**Comment by httpJunkie** [comment]
Question 1:

case 1:
// array of 1 string delimit with comma will not work as expected.
select: ['operational, callsign, name, info.numberOfFlightsSince'],

case 2:
// string delimit with comma will work ok
select: 'operational, callsign, name, info.numberOfFlightsSince',

case 3:
// array of string will work ok
select: ['operational', 'callsign', 'name', 'info.numberOfFlightsSince']

Question 2:
Returning with default values was a bug and was fixed in version alpha.12

Question 3:
This is the default behavior. If a different behavior is expected we would like to have a strong case why.

**Comment by bwgjoseph** [comment]
I have tested using `1` and it actually works

```js
const find2 = await Airplane.find(
{},
{
	select: ['operational, callsign, name, info.numberOfFlightsSince'],
	consistency: SearchConsistency.LOCAL
});

// returns
rows: [
	_Model {
	  _type: 'Airplane',
	  callsign: 'Hawk',
	  name: 'Couchbase Airlines',
	  operational: true
	}
]
```

You can find the test case in

https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/dede17cf166944282d682bb896df3fa16f820678/test/ts/%24select.test.ts#L127
https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/dede17cf166944282d682bb896df3fa16f820678/test/ts/%24select.test.ts#L155
https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/dede17cf166944282d682bb896df3fa16f820678/test/ts/%24select.test.ts#L183

---

Yup, looking good now

---

There's 2 scenario that I can think of right now.

1. Deviate from original schema

This will probably cause issue in languages like `typescript` where we declare interface/schema/model but the result returns as unexpected (doesn't match) the defined interface. And it will be worst for language like `Java` where it requires matching class (POJO) fields to be able to map correct for (JSON) serialization and deserialization.

```js
// image the interface defined as such
interface AirplaneInfo {
    firstFlightAt: Date;
    callsign?: string;
}

interface AirplaneInterface {
	callsign: string;
	name: string;
	info: AirplaneInfo;
}

// perform a find with nested
const find = await Airplane.find(
            {},
            {
                select: 'info.callsign',
                consistency: SearchConsistency.LOCAL
            });

// and it returns, it does not match the signature
{"_type":"Airplane","callsign":"Hawk2"}
```

2. Name clashing

Using back the same interface defined above, and let's try to run a select as such

```js
const find = await Airplane.find(
	{},
	{
		select: 'callsign, info.callsign',
		consistency: SearchConsistency.LOCAL
});
```

`ottoman` actually throws an error 

```js
1) test $select function
   ottoman - $select root and nested object with same field name:
 Error: parsing failure
  at _getWrappedErr (node_modules\couchbase\lib\errors.js:830:14)
  at Object.wrapLcbErr (node_modules\couchbase\lib\errors.js:1009:20)
  at Z:\mongoose-vs-ottoman\node_modules\couchbase\lib\queryexecutor.js:126:26
```

Even if it does not, how should it be handled, if selecting the nested object field returns as a root element?

You can find the test case in https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/dede17cf166944282d682bb896df3fa16f820678/test/ts/%24select.test.ts#L211

**Comment by AV25242** [comment]
@bwgjoseph  thats correct, try to use alias name like you would in SQL. 

`select: 'callsign, info.callsign as sign',`

**Comment by bwgjoseph** [comment]
That doesn't solve the problem on hand by using alias. This would then cause issue as mentioned in `1`. 

Using alias might be fine for `javascript` but not `typescript` or `java` as described

```js
const find = await Airplane.find(
	{},
	{
		select: 'callsign, info.callsign as sign',
		consistency: SearchConsistency.LOCAL
	});
const plane: AirplaneInterface = find.rows[0];
```

![image](https://user-images.githubusercontent.com/37484538/103908803-e282a600-513d-11eb-857c-33ab16b7b98e.png)

I could cast it to `any` - like `(x as any).sign` as a workaround but that defeats the purpose of having typed

I haven't used `Java` with SQL for a quite some time, and I'm not aware of any way that you could map back the field to a POJO that does not belong to the POJO class that you declare since the field doesn't exist in the first place.

**Comment by AV25242** [comment]
@bwgjoseph  the find with select uses N1QL query behind the scenes. you can achieve objects back if not nested 
for instance try
`select : 'callsign, { info.callsign } as info' `

**Comment by httpJunkie** [comment]
Here is an example of the query and results of this approach in action: 

**N1QL Query:** 
```
SELECT {"something": {a.geo.something.elsexxx, a.geo.something.elseyyy}, geo.lat} as geo 
FROM `travel-sample` a 
WHERE a.type = "hotel" 
AND a.id = 10025
```

**Result:** 
```[
  {
    "geo": {
      "lat": 51.35785,
      "something": {
        "elsexxx": 1234
      }
    }
  }
]```

**Comment by bwgjoseph** [comment]
I have verified this to be working, thank you!
